\documentclass[12pt,titlepage]{article}
\usepackage{amsmath}
\usepackage{siunitx}
\usepackage{import}
\usepackage{authblk}

%Images
\usepackage{subcaption}
\usepackage{pgfplots}
\usepackage{colortbl}

%Journal font & paper requirements
\usepackage{newtxtext} %Times New Roman
\usepackage[letterpaper,margin=1in]{geometry}

%Preprint
\usepackage{lineno} \linenumbers
\usepackage{setspace} \doublespacing
\usepackage[nomarkers,tablesfirst,notablist]{endfloat}
\addtodelayedfloat{figure}{\clearpage} %Each delayed figure on a new page.

%Ensure title page is numbered, as journal style requires it.
%Using https://tex.stackexchange.com/a/172005, adapted not to bother with two column stuff.
\makeatletter
\renewenvironment{titlepage}{\thispagestyle{plain}}{\newpage}
\makeatother

%Referencing
\import{reference-styles/}{ecology.tex}
\addbibresource{bibliography/references.bib}
\addbibresource{references.bib}
\usepackage{placeins} %Provides \FloatBarrier

\usepackage{hyperref}
\usepackage{cleveref}

%Title Page
\title{Regularising Lotka--Volterra interaction matrices by species grouping: optimal groupings are unpredictable} %TODO: Remove the word "regularising" from the title.
\author{Christopher R.\ P.\ Brown}
\author{Daniel B.\ Stouffer}
\affil{Centre for Integrative Ecology, School of Biological Sciences, University of Canterbury, Christchurch, New Zealand}
\date{}

<<include=FALSE>>=
	knitr::opts_chunk$set(results = 'asis') #Text is grey without this.
	knit_hooks$set(inline = function(x) {x}) #Disable automatic formatting of in-line material.
@

<<include=FALSE>>=
	source("r/post-process.R")
	source("r/brute-post-process.R")
	source("r/mantel-test.R")
	source("r/dist-matrix.R")
	source("r/coclassification-table.R")
	
	species_dat <- read.csv("data/species.csv")
	species_output_order <- c(4,3,1,2,6,5)
	
	brute_data <- BruteData$new("output/brute.data", species_dat$name)
	
	#Precalculate the coclassification matrices, as these are active bindings and the slowest part of compilation.
	weighted_col_coclassification_matrix <- brute_data$weighted_col_coclassification_matrix
	weighted_row_coclassification_matrix <- brute_data$weighted_row_coclassification_matrix
	
	#Precalculate distances matrices as well.
	col_distance_matrix <- 1 - weighted_col_coclassification_matrix
	row_distance_matrix <- 1 - weighted_row_coclassification_matrix
	body_weight_distance_matrix <- build_dist_matrix(species_dat$name, species_dat$body_weight, function(w1,w2){abs(w1-w2)})
@

\newcommand\rsquarednum[1]{\num[round-mode=places,round-precision=3]{#1}}
\newcommand\aicnum[1]{\num{#1}}
\newcommand\probnum[1]{\num[round-mode=places,round-precision=3]{#1}}
\newcommand\cornum[1]{\num[round-mode=places,round-precision=3]{#1}}

\newcommand\mantelstat{\ensuremath{r_{\text{M}}}}

\newcommand\keywords[1]{\emph{Key words: #1}}

\begin{document}
\maketitle

% DBS: I'll leave the abstract free of comments until the main text is closer to the final version.

\section*{Abstract}

Dynamic models of ecological communities require many parameters, making them expensive to fit.
To reduce the number of parameters, species are often divided into groups \emph{a priori}, using phylogeny or functional groups, and species within a group are assumed to behave identically.
Herein, we assess the validity of such grouping by deriving the optimal groupings \emph{a posteriori}, from the parsimony of a Lotka--Volterra model fit to fecundity data from six competing species of \emph{Drosophila} in laboratory conditions.
We find evidence that grouping can benefit the parsimony of species interaction models, but that there is no single optimal grouping.
Further, those groupings that did prove beneficial could not be predicted from information available \emph{a priori}, calling the method of \emph{a priori} species grouping into question.
Lastly, we find that species did not group equivalently in their competitive effect and in their response to competition, invalidating an assumption often made implicitly when defining species groupings.

\keywords{Lotka--Volterra; interaction matrix; competition; grouping; model fitting; parsimony; phylogeny}

\section{Introduction}

Models have long been used in community ecology \parencite{lotka1925elements}.
They allow us to make predictions about things we cannot directly observe, be it the response of a community to novel pressures \parencite{novak2016characterizing}, or the stability of an entirely novel assemblage \parencite{maynard2020predicting}.
The ability to make these predictions is becoming increasingly important as global change accelerates, introducing alien species and applying climatic or other anthropogenic pressures to communities worldwide \parencite{XXX}.

Making practical use of a model requires experimentally or observationally determining the values of each of the model's parameters.
This poses a particular problem for models that include species interactions due to the sheer number of parameters that must be determined.
Even the simplest models with no environmental dependence require one parameter to characterise the interaction of each pair of species \parencite{novak2016characterizing, XXX}.
Hence the number of parameters scales quadratically with the number of species; at least \num{100} parameters are required for the interactions in a community of ``just'' \num{10} species.
Determining these parameters experimentally requires at least one experiment per parameter, and preferably more \parencite{hart2018quantify}.
This is expensive, and requires a lot of effort.
As such, model-based predictions of real communities are typically restricted to a small number of focal species \parencite{ovaskainen2017species, XXX}.
However, real communities can contain hundreds of species \parencite{cornell1999unsaturation}, or even thousands for microbial communities assessed by genetic metabarcoding \parencite{warton2015variables}.
To bridge this gap between the size of real communities and our ability to parameterise them, we need an ecologically-defensible way to reduce the number of parameters that predictive models require.

One simplifying approach is to assume that most pairs of species do not interact or interact weakly, and hence setting many of the parameters to zero \parencite{mutshinda2009drives}.
%TODO: XXX why this could be a problem XXX.
Alternatively, one can assume that species fall into groups, such that all species in the same group interact with species in other groups in an identical fashion, thereby collapsing pairwise interaction parameters for all the species in that group into sets of common parameters \parencite{ovaskainen2017species,weiss2021disentangling}.

In ecological contexts, such groups have been defined \emph{a priori} by phylogeny at some taxonomic level or by functional groupings \parencite{uriarte2004spatially,ovaskainen2017species,weiss2021disentangling}.
The argument for grouping based on phylogeny relies on the principle that closely related species will fill similar ecological niches, and hence will interact with other species in a similar fashion \parencite{godoy2014phylogenetic}.
However, empirical tests of this principle have found remarkably little support for it \parencite{godoy2014phylogenetic,cahill2008does,mayfield2010opposing}.
On the other hand, functional groupings have also proven to be poor predictors of species interactions \parencite{bret2008plant}.
While attempts have been made to define functional groupings that are more useful in a modelling context \parencite{boulangeat2012improving}, these rely upon measurements of biotic interactions to define such groups.
As such, integrating these into species interaction models leaves us with a circular argument: a functional group is a group of species that interact with others in a similar way, and we therefore assume that all the species in a functional group interact with others in a similar way.
In all, we are left with the question of how best to group species in community models, and whether we can do so in a meaningful way using less data than required for a fully pairwise parameterisation.

Additionally, studies that use grouping to simplify models of species interactions have always made one untested assumption: that the same grouping is equally valid for how species affect others as for how spcies respond to others \parencite{XXX}.
There is good reason to question this assumption, as it is known that different traits can govern species' competitive effects than govern their responses to competition \parencite{goldberg1991competitive}.
As such, the best groupings of species may be different for each of the effects and responses.

We propose that species might be best partitioned into groups without regard to any \emph{a priori} definition but instead based purely upon which grouping gives the most parsimonious model.
% DBS: We can say something here about how this data-informed approach has worked very well for other clustering problems, such as modularity in networks. I can point to some very good references along those lines.
In this study, we investigate the usefulness and correctness of such an approach using experimental \emph{Drosophila} fecundity data provided by \textcite{terry2021natural}.
We fit the Lotka--Volterra model, with grouped species, to find the grouping that gives the most parsimonious model.
We group species independently with regard to their effects upon other species and their responses to other species, to find whether the appropriate groupings might differ for these two cases.
%TODO: Mention the comparison to traits (body size)?

\section{Methods}

\subsection{Data}

The data we used in this study were drawn from the work of \textcite{terry2021natural}.
The data consist of fecundity measurements---number of surviving offspring---for six species of \emph{Drosophila}, grown in single-species or two-species communities with varying densities of each species.
This experimental design corresponds to a response--surface experimental design commonly used to parameterise a species interaction model \parencite{hart2018quantify, XXX}.

We shall not repeat the entire experimental methodology here---refer to \textcite{terry2021natural} for that---but provide a summary of the pertinent points.

\subsubsection{Summary of the experimental methodology}

The experiment used six species of \emph{Drosophila} from an Australian rainforest community: \emph{D. birchii}, \emph{D. pallidifrons}, \emph{D. pandora}, \emph{D. pseudoananassae}, \emph{D. simulans}, and \emph{D. sulfurigaster}.
The experiment took place in vials with a limited amount of medium for egg-laying and larval development; competition was for space on this medium.
A fixed number of adult pairs of one or two species were added to each vial and allowed to mate and lay eggs.
The number of adult pairs of each species emerging from these eggs was counted---this was the size of the next generation.

Experiments occurred for every single-species and two-species combination of the six species, at a variety of densities.
The single-species densities were 3, 9, or 12 pairs per vial, each replicated six times per species.
The two-species densities were, giving the densities of each of the two species, (3,3), (3,6), (3,9), (3,12), (6,3), (9,3), or (12,3) pairs per vial, each replicated three times per pair of species.
Vials with a single founding pair were excluded from this study and the original authors' due to an Allee effect that the Lotka--Volterra model cannot accommodate.

Further details of the experimental methodology can be found in \textcite{terry2021natural}.

\subsection{Model}

The data provided the change population size from one generation to the next, so we used a discrete-time version of the Lotka--Volterra competition model given by:
\[
	N_{i,t+1} - N_{i,t} = N_{i,t} r_i \left(1 - \sum_j \alpha_{ij} N_{j,t}\right)
,\]
where $N_{i,t}$ is the population of species $i$ at time $t$ (the size of the parent generation), $N_{i,t+1}$ is the population at time $t+1$ (the size of the offspring generation), $r_i$ is the intrinsic growth rate of species $i$, and $\alpha_{ij}$ is the \emph{per capita} competitive effect of species $j$ on species $i$.
The competition coefficients were not constrained to be positive, allowing for the possibility of mutualistic effects between some species.

% DBS: We might want to be prepared for reviewers asking us to change from a linear LV model.

\subsubsection{Species grouping}

In order to reduce the number of free parameters in the model, we grouped species together, and constrained the appropriate competition coefficients to be equal for species within the same group.

A grouping, known as a partition in mathematics, divides the species into groups such that each species belongs to one and only one group.
Given $n$ species, there may be any integer number of groups from $1$ to $n$.
With $n$ groups, the grouping places each species into its own group, such that all species interact in a unique fashion.
With $1$ group, every species is placed in the same group, such that all are equal in their interactions, reminiscent of the neutral model.

We did not assume that species should be grouped the same in their competitive effects as in their competitive responses.
As such, each model was defined by two groupings: a grouping of species constraining equivalence in their competitive effects, and a second, independent grouping of species constraining equivalence in their competitive responses.

The set of competition coefficients in the Lotka--Volterra model can be arranged in an interaction matrix \parencite{novak2016characterizing}, where a row contains all the competitive effects on a single species and a column contains all the competitive effects of a single species.
As such, if two species are in the same group regarding their competitive responses, then two rows of the interaction matrix are constrained to be equal.
Similarly, if two species are in the same group regarding their competitive effects, then two columns of the interaction matrix are constrained to be equal.
This allows us to refer simply to the ``row grouping'' and the ``column grouping''.
Formally, if species $a$ and $b$ were in the same column group, $\alpha_{ia}\equiv\alpha_{ib} \, \forall i$, and if $a$ and $b$ were in the same row group, $\alpha_{aj}\equiv\alpha_{bj} \, \forall j$.
As such, the total number of free competition coefficients in the model was equal to the number of row groups multiplied by the number of column groups.
The species' intrinsic growth rates, $r_i$, were not affected by grouping; each species always had its own growth rate fitted independently of other species.

The total number of groupings for $n$ species is given by the Bell numbers, denoted $B_n$ \parencite{bell1934exponential}.
With six species and independently selected row and column groupings, the total number of possible models is ${\left(B_6\right)}^2 = \num{\Sexpr{numbers::bell(6)^2}}$.

\subsubsection{Model fitting}

The Lotka--Volterra model is not linear in the parameters.
With the rows of the interaction matrix ungrouped, the regression could be reparameterised to be linear in the parameters by treating $r_i \alpha_{ij}$ as a single regression parameter for each $i,j$ pair.
With the rows grouped, however, this becomes impossible, since each species still has an independent growth rate.
As such, the models were fitted by the Gauss--Newton method for non-linear least squares.
%The models were fitted to the data using maximum likelihood regression techniques.
%Fitting it using precisely a Lotka--Volterra model prevented the use of a link function, rendering most generalised regression techniques infeasible.
We assumed a normal error distribution of the response variable and to prevent heteroskedasticity and improve normality, we transformed total population growth to \emph{per capita} population growth, which corresponds to the following model:
\[
	\frac{N_{i,t+1} - N_{i,t}}{N_{i,t}} = r_i \left(1 - \sum_j \alpha_{ij} N_{j,t}\right)
.\]

\subsubsection{Assessing parsimony}

To assess the parsimony of the different species groupings, we exhaustively fit all \num{\Sexpr{numbers::bell(6)^2}} possible models.
As a measure of parsimony, we selected AIC over BIC on the basis that we want to find the best model for making ecological predictions, rather than seeking the ``true'' model \parencite{aho2014model}.
Further, AIC is more conservative in promoting grouping, as BIC penalises number of parameters more for any reasonably sized data set.
As such, we calculated the AIC for each model.
% DBS: Is it possible that the dataset is small enough that we should be using AICc instead?

AIC values can be compared to determine which model is the most parsimonious, but cannot directly be interpreted to find the significance of the difference in parsimony.
As such, we also converted the set of AIC values to Akaike weights \parencite{wagenmakers2004aic}.
These give the probability that each model is the best among the models assessed.

From the Akaike weights, we calculated two important statistics.
Firstly, the total Akaike weight of models with a lower AIC than the entirely ungrouped model; this is the probability that some model is more parsimonious than the ungrouped model.
Secondly, the total Akaike weight of models that used the same grouping for the rows as for the columns; this is the probability that the most parsimonious model grouped species equivalently in their competitive effects as in their competitive responses.
To evaluate the significance of the latter, we performed a Monte Carlo permutation test, comparing the total Akaike weight of those models that grouped rows and columns equivalently to the total Akaike weight of a random equally-sized subset of the models.
%This is a test of whether the most parsimonious model is more likely to group the species equivalently in the rows as in the columns than it would be by chance.
%TODO: Is this test superseded by the Mantel test of row vs column coclassification?
%TODO: Should this test simply be a t-test on the raw AIC values? I think not, as we're interested in the best, rather than the mean.

\subsubsection{Coclassification matrices}

To summarise the results, the Akaike weights were used to generate coclassification matrices, one for the row groupings and one for the column groupings.
Each cell of a coclassification matrix represents the coclassification of two species, and contains the total Akaike weight of models that place those two species in the same group.
As such, each cell represents the probability that the most parsimonious model is one that coclassifies those two species.

There are a number of possible ``null'' expectations for these matrices.
A neutral model approach would expect all species to be the same: every cell would be $1$.
If each species were expected to be unique, every off-diagonal cell would be $0$.
Alternatively, if every possible grouping were considered to be equally likely, every off-diagonal cell would be $\frac{B_{n-1}}{B_n}$: \probnum{\Sexpr{numbers::bell(5)/numbers::bell(6)}} for six species.
Unfortunately, without a null distribution, it was impossible to test the empirical coclassification matrices against a null expectation.

However, we could test the coclassification matrices against one another.
By testing for correlation between the coclassification matrix for the the rows and that for the columns, we could test the assumption that it is appropriate to use the same grouping for both.
We did this using a Mantel test, as appropriate for similarity matrices.

We could also test the coclassification matrices for correlation with an expected dissimilarity matrix.
We calculated one such dissimilarity matrix based on a species trait: body size (as mean wet mass of female adults, obtained from \cite{terry2021natural}).
The trait difference matrix was calculated as absolute difference between trait values, while the coclassification matrices were converted to dissimilarity matrices by subtracting from $1$.
We performed a Mantel test for correlation between the trait distance matrix and each of the two coclassification dissimilarity matrices.

\section{Results}

The $R^2$ values of the models ranged from \rsquarednum{\Sexpr{min(brute_data$statistics$R2)}} to \rsquarednum{\Sexpr{max(brute_data$statistics$R2)}}.
The AIC values ranged from \aicnum{\Sexpr{min(brute_data$statistics$aic)}} to \aicnum{\Sexpr{max(brute_data$statistics$aic)}}.
The ungrouped model gave an AIC value of \aicnum{\Sexpr{brute_data$fully_separated_statistics$aic}}.
\Cref{fig:aic} shows the distribution of AIC values from the models, with some models of interest marked.

\begin{figure}
	<<echo=FALSE>>=
		hist(brute_data$statistics$aic,
			main="",
			xlab="AIC",
			xaxs='i',
			yaxs='i'
		)
		abline(v = brute_data$fully_separated_statistics$aic, lwd=2, lty="dashed", col="green")
		abline(v = brute_data$fully_grouped_statistics$aic, lwd=2, lty="dashed", col="red")
	@
	
	\caption{%
		A histogram of the AIC values of species interaction models with all possible groupings of interaction coefficients.
		The green line shows the AIC value (\aicnum{\Sexpr{brute_data$fully_separated_statistics$aic}}) of the ungrouped model, in which all competition coefficients are fitted independently.
		The red line shows the AIC value (\aicnum{\Sexpr{brute_data$fully_grouped_statistics$aic}}) of the fully grouped model, where every pair of species shares a single interaction coefficient.
	}
	\label{fig:aic}
\end{figure}

The ``best'' model, as indicated by AIC, was not the best with any surety; its Akaike weight indicated a probability of only \probnum{\Sexpr{max(brute_data$statistics$aic_weight)}} that it was the best.
The total Akaike weight assigned to models more parsimonious than the ungrouped model was \probnum{\Sexpr{sum(brute_data$statistics$aic_weight[brute_data$statistics$aic < brute_data$fully_separated_statistics$aic])}}; this is the probability that some grouped model was more parsimonious than the ungrouped model.

Considering only models in which the rows and columns were grouped using the same grouping, the AIC values ranged from \aicnum{\Sexpr{min(brute_data$equivalently_grouped_statistics$aic)}} to \aicnum{\Sexpr{max(brute_data$equivalently_grouped_statistics$aic)}}; neither the best nor worst overall models had equivalently grouped rows and columns.
The total Akaike weight assigned to these models was \probnum{\Sexpr{brute_data$equivalently_grouped_weight}}; more than expected by chance (\probnum{\Sexpr{brute_data$equivalently_grouped_expected_weight}}), but not significantly so (Monte Carlo permutation test, $p=\probnum{\Sexpr{brute_data$equivalently_grouped_weight_p #$}}$).
This indicates that the most parsimonious model is not especially likely to be one that groups the rows and columns equivalently.

\subsection{Coclassification of species}

Coclassification matrices for the row and column groupings are shown in \cref{fig:coclassification}.
In all, no pair of species can confidently be said to be coclassified, in the row or column groupings; no probability of coclassification exceeded \SI{75}{\percent}.
Some pairs of species were far more likely to be coclassified than others, however, suggesting some structure to the best groupings.

The structure of the coclassifications was very different in the row groups than in the column groups.
Most pairs of species which had a high probability of being coclassified in one grouping had a very low probability of being coclassified in the other grouping.
Only one pair of species had a relatively high probability of being coclassified in both groupings: \emph{D. pallidifrons} and \emph{D. sulfurigaster}.
Overall, more coclassification occurred in the row groupings than in the column groupings.
A Mantel test of the coclassification matrix for the rows against that for the columns shows that there is no significant correlation between the two ($\mantelstat=\cornum{\Sexpr{mantel_cor(weighted_col_coclassification_matrix, weighted_row_coclassification_matrix)}}$, $p=\probnum{\Sexpr{mantel_p(weighted_col_coclassification_matrix, weighted_row_coclassification_matrix)}}$).

A relatively high likelihood of coclassification in the row groupings was typically transitive: e.g.\ \emph{D. birchii}, \emph{D. pallidifrons} and \emph{D. sulfurigaster} each had a relatively high probability of being coclassified with one another.
More intransitivity was observed in the column groupings: \emph{D. pallidifrons} had a relatively high probability of being coclassified with \emph{D. sulfurigaster}, and \emph{D. sulfurigaster} had a substantial probability of being coclassified with \emph{D. simulans}, but \emph{D. pallidifrons} had a much lower probability of being coclassified with \emph{D. simulans}.

Neither the row nor column coclassification matrix was significantly correlated with a dissimilarity matrix based on species body size (column: $\mantelstat=\cornum{\Sexpr{mantel_cor(col_distance_matrix, body_weight_distance_matrix)}}$, $p=\probnum{\Sexpr{mantel_p(col_distance_matrix, body_weight_distance_matrix)}}$; row: $\mantelstat=\cornum{\Sexpr{mantel_cor(row_distance_matrix, body_weight_distance_matrix)}}$, $p=\probnum{\Sexpr{mantel_p(row_distance_matrix, body_weight_distance_matrix)}}$).

\pgfplotsset{%
	colormap={coclassification}{color=(white) color=(red)}
}
\colorlet{coclassification diagonal}{black!20}
\begin{figure}
	\centering
	\begin{subfigure}{\textwidth}
		\centering
		<<echo=FALSE>>=
			weighted_coclassification_kable(
				weighted_col_coclassification_matrix[species_output_order,species_output_order],
				colourmap="coclassification", diagonal_colour="coclassification diagonal"
			)
		@
		\caption{Weighted coclassification of competitive effects (columns of the interaction matrix).}
		\label{fig:coclassification-cols}
	\end{subfigure}
	
	\bigskip
	
	\begin{subfigure}{\textwidth}
		\centering
		<<echo=FALSE>>=
			weighted_coclassification_kable(
				weighted_row_coclassification_matrix[species_output_order,species_output_order],
				colourmap="coclassification", diagonal_colour="coclassification diagonal"
			)
		@
		\caption{Weighted coclassification of competitive responses (rows of the interaction matrix).}
		\label{fig:coclassification-rows}
	\end{subfigure}
	
	\caption{%
		Coclassification matrices of the Lotka--Volterra competitive effects and responses of the six studied \emph{Drosophila} species, weighted by AIC weights.
		The cell for a pair of species represents the probability that the best grouping, as determined by the AIC weights of the grouped models, places those two species in the same group.
		\Cref{fig:coclassification-cols} represents the grouping of species' competitive effects upon other species (columns of the interaction matrix), while \cref{fig:coclassification-rows} represents the grouping of species' responses to competition (rows of the interaction matrix).
	}
	\label{fig:coclassification}
\end{figure}

% DBS: I think a good figure would be to show the ungrouped estimated alpha matrix in one panel and the alpha matrix averaged across all partitions in a second panel, with lines drawn in the second to reflect the "optimal" partitioning of the co-classification matrices.

\section{Discussion}

We have shown that it is possible to fit a more parsimonious model of species interactions by grouping the interaction coefficients of species \emph{a posteriori}, and hence reducing the number of free parameters in the model.
The results show that grouping the interaction coefficients of species was likely to give a more parsimonious model (probability \probnum{\Sexpr{sum(brute_data$statistics$aic_weight[brute_data$statistics$aic < brute_data$fully_separated_statistics$aic])}}) than leaving them ungrouped, but not confidently so.
Which grouping might give the most parsimonious model also could not be determined with any confidence.
% DBS: The two preceding sentences are very glass half empty. I'm also not sure that the results are really so equivocal. What makes you feel this way?
The intransitivity of coclassification in some instances even suggests that there may not be a single ``best'' grouping, but rather two or more quite distinct and mutually exclusive groupings of similar validity.
% DBS: In my mind, I would steal the preceding sentence and spin it potentially spin it into its own paragraph later since it speaks strongly to a mixed-membership approach which could be sold as a "future direction".

% DBS: Avoid imprecise "this" or "that" as subjects. Always say "This result" or something similar. Also, avoid starting a new paragraph that so strongly forms a continuation of the previous one.
This stands in contrast to the popular wisdom in ecology that species should form some sort of clear groups, be they the functional groups so often used \parencite{blondel2003guilds}, or taxonomic groups per a relationship between phylogeny and ecological niche \parencite{godoy2014phylogenetic}.
It also contrasts with previous studies that have succeeded in finding clear groups, such as \textcite{allesina2009food}, who used AIC to find the best grouping of species, but in a binary food web rather than a quantitative competitive context.
Perhaps species simply do not group to the same extent in a competitive context.
The results suggest that this is unlikely, as grouping was still likely to increase parsimony.
Further, there is no reason to suspect that species would not have clear similarities or dissimilarities in their ecological niches, and therefore their competitive effects and responses.
Perhaps the lack of clarity in the groupings is instead a product of the study system chosen.

%TODO: Discuss the potential to study a system with functional groups without brining up phylogeny.
%I chose a study system of \emph{Drosophila} partially on the basis that it would allow clear analysis of the species' phylogenetic relationships.
%Phylogeny proved a poor predictor of optimal grouping, as previous studies have suggested that it might \parencite{godoy2014phylogenetic,cahill2008does}.
%A study system with species spanning multiple functional groups, however, might have shown clearer groupings.
%While functional groups have previously shown to be poor predictors of competitive interactions \parencite{bret2008plant}, studies in other contexts have succeeded in isolating functional groups by selecting for model parsimony \parencite{allesina2009food}.
%In further support of functional groups over phylogeny, \textcite{uriarte2004spatially} found that grouping based on light guilds (akin to functional groups; \cite{blondel2003guilds}) produced a parsimonious model more frequently than grouping taxonomically (with both groupings defined \emph{a priori}).
%Perhaps an attempt to produce functional groups based upon competitive interactions is warranted, applying the framework we present here to a set of species spanning multiple functional groups.
% DBS: Prolix warning! ;)

Alternatively, it should be noted that the success of \textcite{allesina2009food} in isolating groups using AIC occurred in much larger study systems, with 25 or more species.
% DBS: Personally, I try to make links to previous studies more self contained. Since the Allesina paper and its use of AIC was brought up earlier, it strikes me as repetitive to lean on it alone again here.
Alas, the brute force method we employed in this study has a very poor algorithmic complexity, preventing the application of the method to studies with more than seven or eight species.
As such, a better method would be required in order to test for grouping of species interactions among a larger set of species.

% DBS: The paragraph below is a very good example of text that could easily be simplified for clarity without losing important content.
In light of the failure to produce clear groups, perhaps the most curious aspect of the results is the disagreement between the likely coclassifications of species in the groupings of rows and of columns.
This is perhaps not surprising in hindsight, for there is no necessity that species respond to competition in the same manner that they cause it, especially in competition for certain resources such as space (the limiting resource presumed in these data) or light. % DBS: Some definite refs missing here.
Yet the assumption that species should group equivalently in these two regards is frequently made, often implicitly and without comment \parencite[e.g.][]{martorell2014testing,ives2003estimating,gross2015stability}.
My results recommend more explicit questioning, and even testing, of that assumption when building future species interaction models.
%TODO: Discuss the fact that species were coclassified more in the rows than in the columns.

All in all, the method of \emph{a posteriori} parsimony-based selection of groups has not proven to be greatly effective, at least on such a closely related set of species.
However, the results suggest some advice which might be borne in mind whenever selecting groupings \emph{a priori} for use in species interaction models.
Firstly, there may be no single best grouping, but perhaps multiple rather distinct groupings which each perform similarly.
Furthermore, one should not implicitly assume that species are grouped in the same way with regard to their effects upon other species and their response to them; distinct groupings of the two might well be considered.

\FloatBarrier
\printbibliography
\end{document}
