#!/usr/bin/env Rscript

suppressPackageStartupMessages(library(optparse))

this_dir <- dirname(this.path::this.path())
source(paste0(this_dir, "/r/parameters.R"))
source(paste0(this_dir, "/r/input-data.R"))
source(paste0(this_dir, "/r/post-process.R"))
source(paste0(this_dir, "/r/rjmcmc-post-process.R"))
source(paste0(this_dir, "/r/coclassification-table.R"))

##################
#Argument parsing.
##################

usage = "%prog [options] OUTPUT_FILE"
description = "Performs all the heavy analysis for the article and supplementary rnw files, and saves it as a .rda file."
option_list <- list()
parser <- OptionParser(usage = usage, description=description, option_list=option_list)
arguments <- parse_args(parser, positional_arguments = 1)

outfile <- arguments$args[1]

attach(arguments$options)

##########
#Analysis.
##########

tcl_species_data <- read.csv(paste0(this_dir, "/data/tcl-species.csv"))
cxr_species_data <- read.csv(paste0(this_dir, "/output/cxr-species.csv"))
goldberg_species_data <- read.csv(paste0(this_dir, "/data/goldberg-species.csv"))

tcl_data <- RJMCMCData$new(paste0(this_dir, "/output/tcl/rjmcmc.data"), tcl_species_data$name)
cxr_data <- RJMCMCData$new(paste0(this_dir, "/output/cxr/rjmcmc.data"), cxr_species_data$name)
goldberg_data <- RJMCMCData$new(paste0(this_dir, "/output/goldberg/rjmcmc.data"), goldberg_species_data$name)

tcl_output_order <- c(4,3,1,2,6,5)
cxr_output_order <- c(8,7,1,2,3,6,5,4,9)
goldberg_output_order <- c(1,5,3,6,7,2,4)

datasets <- list("tcl", "cxr", "goldberg")
names(datasets) <- datasets

#########
#Figures.
#########

coclassification_colourmap <- "coclassification"
coclassification_diagonal_colour <- "coclassification diagonal"
coclassification_colour_setup <- paste0(
	"\\pgfplotsset{colormap={",coclassification_colourmap,"}{color=(white) color=(red)}}\n",
	"\\colorlet{",coclassification_diagonal_colour,"}{black!20}\n"
)

get_coclassification_matrices <- function(data, output_order) {
	lapply(
		list(
			row = data$weighted_row_coclassification_matrix,
			col = data$weighted_col_coclassification_matrix
		),
		function(mat) {
			output_order <- output_order[output_order <= nrow(mat)]
			weighted_coclassification_kable(
				mat[output_order,output_order],
				colourmap="coclassification", diagonal_colour="coclassification diagonal"
			)
		}
	)
}

coclassification_matrices <- lapply(datasets, function(name) {
	get_coclassification_matrices(eval(parse(text=paste0(name,"_data"))), eval(parse(text=paste0(name,"_output_order"))))
})

#############
#Save output.
#############

print(ls())

save(list = ls(), file = outfile)
