\documentclass[12pt,titlepage]{article}
\usepackage{amsmath}
\usepackage{siunitx}
\usepackage{import}
\usepackage{authblk}

%Images & tables
\usepackage{subcaption}
\usepackage{pgfplots}
\usepackage{colortbl}
\usepackage{multirow}
\usepackage{arydshln}

\captionsetup{subrefformat=parens} %Changes only \subref, not \ref.
\let\Subref\subref
%TODO: Make \cref figure out if it should be a subref, and use cref throughout.

%Journal font & paper requirements
\usepackage{newtxtext} %Times New Roman
\usepackage[letterpaper,margin=1in]{geometry}

%Preprint
\usepackage{lineno} \linenumbers
\usepackage{setspace} \doublespacing
\usepackage[nomarkers,tablesfirst,notablist,nofiglist]{endfloat}
\addtodelayedfloat{figure}{\clearpage} %Each delayed figure on a new page.

%Ensure title page is numbered, as journal style requires it.
%Using https://tex.stackexchange.com/a/172005, adapted not to bother with two column stuff.
\makeatletter
\renewenvironment{titlepage}{\thispagestyle{plain}}{\newpage}
\makeatother

%Referencing
\import{reference-styles/}{ecology.tex}
\addbibresource{bibliography/references.bib}
\addbibresource{references.bib}
\usepackage{placeins} %Provides \FloatBarrier

\usepackage{hyperref}
\usepackage{cleveref}

%Title Page
\title{Simplifying Lotka--Volterra interaction matrices by species grouping: optimal groupings are unpredictable}
\author{Christopher R.\ P.\ Brown}
\author{Daniel B.\ Stouffer}
\affil{Centre for Integrative Ecology, School of Biological Sciences, University of Canterbury, Christchurch, New Zealand}
\date{}

<<include=FALSE>>=
	knitr::opts_chunk$set(echo = FALSE) #Never show the code, only output.
	knitr::opts_chunk$set(results = 'asis') #Text is grey without this.
	knit_hooks$set(inline = function(x) {x}) #Disable automatic formatting of in-line material.
@

<<include=FALSE>>=
	source("r/parameters.R")
	source("r/input-data.R")
	source("r/post-process.R")
	source("r/brute-post-process.R")
	source("r/mantel-test.R")
	source("r/dist-matrix.R")
	source("r/coclassification-table.R")
	source("r/grouped-matrix.R")
	
	species_dat <- read.csv("data/species.csv")
	species_output_order <- c(4,3,1,2,6,5)
	
	input_data <- InputData$new("output/focal-vector.data", "output/response-vector.data", "output/design-matrix.data", is_per_capita=TRUE)
	
	num_species <- input_data$num_species
	num_obs <- input_data$num_obs
	
	ic <- "aicc" #The information criterion to use, e.g. "aic" or "aicc"
	ic_weight <- sprintf("%s_weight", ic)
	ic_name <- list(aic="AIC", aicc="AICc")[[ic]]
	
	brute_data <- BruteData$new("output/brute.data", species_dat$name, ic_weight)
	
	#Precalculate the coclassification matrices, as these are active bindings and the slowest part of compilation.
	weighted_col_coclassification_matrix <- brute_data$weighted_col_coclassification_matrix
	weighted_row_coclassification_matrix <- brute_data$weighted_row_coclassification_matrix
	
	#Precalculate distances matrices as well.
	col_distance_matrix <- 1 - weighted_col_coclassification_matrix
	row_distance_matrix <- 1 - weighted_row_coclassification_matrix
	body_weight_distance_matrix <- build_dist_matrix(species_dat$name, species_dat$body_weight, function(w1,w2){abs(w1-w2)})
@

\newcommand\ic{\Sexpr{ic_name}}

\newcommand\rsquarednum[1]{\num[round-mode=places,round-precision=3]{#1}}
\newcommand\icnum[1]{\num[round-mode=places,round-precision=2]{#1}} %For information criteria.
\newcommand\probnum[1]{\num[round-mode=places,round-precision=3]{#1}}
\newcommand\cornum[1]{\num[round-mode=places,round-precision=3]{#1}}

\newcommand\mantelstat{\ensuremath{r_{\text{M}}}}

\newcommand\keywords[1]{\emph{Key words: #1}}

\pgfplotsset{%
	colormap={coclassification}{color=(white) color=(red)}
}
\colorlet{coclassification diagonal}{black!20}

\begin{document}
\maketitle

\section*{Abstract}

Dynamic models of ecological communities require many parameters, making them expensive to fit to experimental or observational data.
To reduce the number of parameters, species are often divided into groups \emph{a priori}, using phylogenetic or functional groups, and species within a group are assumed to behave identically.
Here, we assess the validity of such grouping by deriving the optimal groupings \emph{a posteriori}, from the parsimony of a Lotka--Volterra model fit to experimental data from six species of \emph{Drosophila} competing in laboratory conditions.
We find evidence that grouping can improve the parsimony of species interaction models, but we also observe that there is no single optimal grouping.
Further, those groupings that did prove beneficial could not be easily predicted from available species attributes \emph{a priori}, calling into question the prevailing method of \emph{a priori} species grouping.
Lastly, we find that species did not group equivalently in their competitive effect and in their response to competition, invalidating a key assumption often made implicitly when defining species groupings.
This suggests the need for a different, more data-informed, approach to grouping in species interaction models.

% DBS: Once we have a title, make sure that we remove all words from the keywords that appear there.
\keywords{Lotka--Volterra; interaction matrix; competition; grouping; model fitting; parsimony}

\section{Introduction}

Models have long been used in community ecology \parencite{lotka1925elements}.
They allow us to make predictions about things we cannot directly observe, be it the response of a community to novel pressures \parencite{novak2016characterizing} or the stability of an entirely novel assemblage \parencite{maynard2020predicting}.
The ability to make these predictions is becoming increasingly important as global change accelerates, introducing alien species and applying climatic or other anthropogenic pressures to communities worldwide \parencite{gilman2010framework,sutherst2007including}.

Making practical use of a model requires experimentally or observationally determining the values of each of the model's parameters.
This poses a particular problem for models that include species interactions due to the sheer number of parameters that must be determined.
Even the simplest models with no environmental dependence require one parameter to characterise the interaction of each pair of species \parencite{novak2016characterizing,rocha2005lotka}.
% DBS: Hmm. Should the above two or rephrased to embrace the directionality of what's going on?
Hence the number of parameters scales quadratically with the number of species; at least \num{100} parameters are required for the interactions in a community of ``just'' \num{10} species.
Determining these parameters experimentally requires at least one experiment per parameter, and preferably more \parencite{hart2018quantify}.
This is understandably expensive and requires substantial effort.
As such, model-based predictions of real communities are typically restricted to a small number of focal species \parencite{ovaskainen2017species,maynard2020predicting}.
However, real communities can contain hundreds of species \parencite{cornell1999unsaturation}, or even thousands for microbial communities assessed by genetic metabarcoding \parencite{warton2015variables}.
To bridge this gap between the size of real communities and our ability to parameterise models for them, we need an ecologically-defensible way to reduce the number of parameters that predictive models require.

One simplifying approach is to assume that most pairs of species do not interact or interact weakly, and hence setting many of the parameters to zero \parencite{mutshinda2009drives}.
However, weak interactions have been shown to be very important to the stability of ecological communities \parencite{mccann1998weak,neutel2002stability,wootton2016many}, and setting these to zero may lose important information.
Another approach assumes that species fall into groups, such that all species in the same group interact with species in other groups in an identical fashion, thereby collapsing pairwise interaction parameters for all the species in that group into sets of common parameters \parencite{ovaskainen2017species,weiss2021disentangling}.

In ecological contexts, such groups have been defined \emph{a priori} by phylogeny at some taxonomic level or by functional similarity \parencite{uriarte2004spatially,ovaskainen2017species,weiss2021disentangling,martyn2021identifying}.
The argument for grouping based on phylogeny relies on the principle that closely related species will fill similar ecological niches, and hence will interact with other species in a similar fashion \parencite{godoy2014phylogenetic,webb2002phylogenies,darwin1859origin}. %Darwin Chapter 3 "Struggle for Life Most Severe Between Individuals and Varieties of the Same Species".
However, empirical tests of this principle have found remarkably little support for it \parencite{godoy2014phylogenetic,cahill2008does,mayfield2010opposing}.
On the other hand, functional groupings have also proven to be poor predictors of species interactions \parencite{bret2008plant,funk2017revisiting}.
While attempts have been made to define functional groupings that are more useful in a modelling context \parencite{boulangeat2012improving}, these rely upon measurements of biotic interactions to define such groups.
As such, integrating these into species interaction models leaves us with a circular argument: a functional group is a group of species that interact with others in a similar way, and we therefore assume that all the species in a functional group interact with others in a similar way.
In all, we are left with the question of how best to group species in community models, and whether we can do so in a meaningful way using less data than required for a fully pairwise parameterisation.

To the best of our knowledge, all studies that use grouping to simplify models of species interactions have also made one additional, untested assumption: that the same grouping is equally valid for how species affect others as for how species respond to others.
There is good reason to question this assumption, as it is known that different traits can govern species' competitive effects than govern their responses to competition \parencite{goldberg1991competitive}.
For resource competition in particular, competitive effect is determined by how the organism affects local resource availability, while competitive response is determined by the organism is inhibited by depleted resources \parencite{violle2009competition}.
As such, the best groupings of species may be different for each of the effects and responses.

We propose that species might be best partitioned into groups without regard to any \emph{a priori} definition but instead based purely upon which grouping gives the most parsimonious model.
Data-informed grouping approaches have previously proved successful in other contexts, such as finding modules in networks \parencite{guimera2005functional,newman2006modularity,girvan2002community}.
In this study, we investigate the usefulness and correctness of such an \emph{a posteriori} approach using experimental data from competition between different \emph{Drosophila} species provided by \textcite{terry2021natural}.
We fit a Lotka--Volterra model to these data to find the groupings that give the most parsimonious model, and compare these groupings to similarity based upon a species trait (body size).
While doing so, we group species independently with regard to their effects upon other species and their responses to other species, to find whether the data-informed groupings differ between these two cases.

\section{Methods}

\subsection{Data}

The data we used in this study were drawn from the work of \textcite{terry2021natural}.
The data consist of fecundity measurements---number of surviving offspring---for six species of \emph{Drosophila}, grown in single-species or two-species communities with varying densities of each species.
This experimental design corresponds to a response--surface experimental design commonly used to parameterise a species interaction model \parencite{hart2018quantify,zhang2019common,cameron2019size}.

\subsubsection{Summary of the experimental methodology}

The experiment used six species of \emph{Drosophila} from an Australian rainforest community: \emph{D. birchii}, \emph{D. pallidifrons}, \emph{D. pandora}, \emph{D. pseudoananassae}, \emph{D. simulans}, and \emph{D. sulfurigaster}.
The experiment took place in vials with a limited amount of medium for egg-laying and larval development; competition was for space on this medium.
A fixed number of adult pairs of one or two species were added to each vial and allowed to mate and lay eggs.
The number of adult pairs of each species emerging from these eggs was counted.

Experiments occurred for every single-species and two-species combination of the six species, at a variety of densities.
The single-species densities were 3, 9, or 12 pairs per vial, and each of these was replicated six times per species.
The two-species densities were (3,3), (3,6), (3,9), (3,12), (6,3), (9,3), or (12,3) pairs per vial (where the paired values give the densities of each of the two species), and each of these was replicated three times per pair of species.
Vials with a single founding pair were excluded from this study and the original authors' due to an Allee effect that the Lotka--Volterra model cannot accommodate.
Further details of the experimental methodology can be found in \textcite{terry2021natural}.

\subsection{Model}

The data provided the change in population size from one generation to the next, so we used a discrete-time version of the Lotka--Volterra competition model given by:
\begin{equation}
	N_{i,t+1} - N_{i,t} = N_{i,t} \, r_i \left(1 - \sum_j \alpha_{ij} N_{j,t}\right) \,,
	\label{eq:lv-model}
\end{equation}
where $N_{i,t}$ is the population of species $i$ at time $t$ (the size of the parent generation), $N_{i,t+1}$ is the population at time $t+1$ (the size of the offspring generation), $r_i$ is the intrinsic growth rate of species $i$, and $\alpha_{ij}$ is the per capita effect of species $j$ on species $i$.
The competition coefficients were not constrained to be positive, allowing for the possibility of mutualistic effects between some species.
With $n$ species, this model has $n+n^2$ parameters: $n$ growth rates and $n^2$ competition coefficients.

% DBS: We might want to be prepared for reviewers asking us to change from a linear LV model.

\subsubsection{Species grouping}

In order to reduce the number of free parameters in the model, we grouped species together, and constrained the appropriate competition coefficients to be equal for species within the same group.
Within the model defined above, each species is effectively in its own group, such that all pairs of species interact in a unique fashion.
At the other extreme, all species could be placed in the same group, such that all pairs of species interact equivalently; they are ecologically equivalent in the sense of \textcite{mcpeek2019disentangling}.
Given $n$ species, there may be any integer number of groups from $1$ to $n$.
Groupings are known formally as partitions in mathematics, and the total number of groupings for $n$ species is given by the Bell numbers, denoted $B_n$ \parencite{bell1934exponential}.

It is commonly assumed that species which are similar in their responses to competition would automatically be similar in their competition effects.
However, competitive responses may be governed by a different set of traits than competitive effects, so this assumption does not necessarily hold.
We avoided this assumption by allowing species which were similar in one regard to be dissimilar in the other, and vice versa.
As such, each model was defined by two groupings of species: one grouping of the competitive responses, and one of the competitive effects.

To better understand the meaning of species grouping of competition coefficients, it is useful to recognise that this component of the Lotka--Volterra model can be represented as an interaction matrix \parencite{novak2016characterizing}, where a row contains all the competitive effects on a single species and a column contains all the competitive effects of a single species.
As such, if two species are assumed to have the same response to competition, then two rows of the interaction matrix are constrained to be equal.
Similarly, if two species are assumed to have the same competitive effect, then two columns of the interaction matrix are constrained to be equal.
This allows us to refer below to the grouping of the competitive responses as the ``row grouping'' and the grouping of the competitive effects as the ``column grouping''.
Formally, if species $a$ and $b$ were in the same row group, $\alpha_{aj}\equiv\alpha_{bj} \, \forall j$, and if $a$ and $b$ were in the same column group, $\alpha_{ia}\equiv\alpha_{ib} \, \forall i$.

With six species and independently selected row and column groupings, the total number of possible models is ${\left(B_6\right)}^2 = \num{\Sexpr{numbers::bell(6)^2}}$.
The species' intrinsic growth rates, $r_i$, were not affected by grouping; each species always had its own growth rate fitted independently of other species.
The total number of parameters in the model is reduced to $n$ growth rates, and a number of competition coefficients equal to the number of row groups multiplied by the number of column groups.

\subsubsection{Model fitting}

The Lotka--Volterra competition model in \cref{eq:lv-model} is not linear in the parameters.
With the rows of the interaction matrix ungrouped, the regression could be reparameterised to be linear in the parameters by treating $r_i \alpha_{ij}$ as a single regression parameter for each $i,j$ pair.
With the rows grouped, however, this becomes impossible since each species still has an independent growth rate.
As such, we instead fit the models with the Gauss--Newton method for non-linear least squares and assumed a normal error distribution of the response variable.
To prevent heteroskedasticity and improve normality, we transformed total population growth to per capita population growth, which corresponds to the following model:
\begin{equation}
	\frac{N_{i,t+1} - N_{i,t}}{N_{i,t}} = r_i \left(1 - \sum_j \alpha_{ij} N_{j,t}\right) \,.
\end{equation}

\subsubsection{Assessing parsimony}

To assess the parsimony of the different species groupings, we exhaustively fit all \num{\Sexpr{numbers::bell(6)^2}} possible models and computed the resulting {\ic} for those fits.
As a measure of parsimony, we selected AICc over BIC on the basis that we want to find the best model for making ecological predictions rather than seeking the ``true'' model \parencite{aho2014model}.
Furthermore, AICc is more conservative in promoting grouping as BIC imposes a greater penalty for the number of parameters for any reasonably sized data set.
Some of the models had a relatively high number of parameters compared to the number of observations (\num{\Sexpr{num_obs}} observations compared to up to \num{\Sexpr{num_species + num_species^2}} parameters), so we used AICc to correct for this ``small sample size'' effect.
{\ic} values can be compared to determine which model is the most parsimonious, but they cannot directly be interpreted to find the significance of the difference in parsimony.
As such, we also converted the set of {\ic} values to Akaike weights \parencite{wagenmakers2004aic}.
These give the probability that each model is the best among the models assessed.

Using these Akaike weights, we calculated two important statistics.
First, the total Akaike weight of models with a lower {\ic} than the entirely ungrouped model; this is the probability that some model is more parsimonious than the fully ungrouped model.
Second, the total Akaike weight of models that used the same grouping for the rows as for the columns; this is the probability that the most parsimonious model grouped species equivalently in their competitive effects as in their competitive responses.
To evaluate the significance of the latter, we performed a Monte Carlo permutation test, comparing the total Akaike weight of those models that grouped rows and columns equivalently to the total Akaike weight of a equally sized random subset of the models.

\subsubsection{Coclassification matrices}

To summarise the results, we also used the Akaike weights to generate two coclassification matrices, one for the row groupings and one for the column groupings.
Each cell of a coclassification matrix represents the coclassification of a pair of species, and contains the total Akaike weight of models that place those two species in the same group.
As such, each cell represents the probability that the most parsimonious model is one that coclassifies those two species.
For reference, note that the diagonal of a coclassification matrix is tautologically equal to $1$.

There are a number of possible ``null'' expectations for the off-diagonal elements these matrices.
A neutral model approach would expect all species to be in the same group: every off-diagonal cell would therefore be $1$.
If each species were expected to be unique, every off-diagonal cell would instead be $0$.
Alternatively, if every possible grouping were considered to be equally likely, every off-diagonal cell would be $\frac{B_{n-1}}{B_n}$: \probnum{\Sexpr{numbers::bell(5)/numbers::bell(6)}} for six species.
Unfortunately, without a null \emph{distribution} of coclassification matrices, it was impossible to test the data-informed coclassification matrices against a null expectation.

However, we could test the row-grouping and column-grouping coclassification matrices against one another.
By testing for correlation between the coclassification matrix for the the rows and that for the columns, we could perform a different test regarding the assumption that it is appropriate to use the same grouping for both.
We did this using a Mantel test, as appropriate for similarity matrices.
We could also test the coclassification matrices for correlation with an expected dissimilarity matrix.
We calculated one such dissimilarity matrix based on a species trait: body size (as mean wet mass of female adults, obtained from \cite{terry2021natural}).
The trait difference matrix was calculated as absolute difference between trait values, while the coclassification matrices were converted to dissimilarity matrices by subtracting them from $1$.
We then performed Mantel tests for correlation between the trait distance matrix and each of the two coclassification dissimilarity matrices.

\section{Results}

% DBS: Should we add a figure that shows the fit of observed vs predicted? Are we forgetting how much that might resonate with readers and jumping ahead too quickly?

% DBS: Semi-random thought: should we also add the "all alphas = 0" model to the mix?

The $R^2$ values of the models ranged from \rsquarednum{\Sexpr{min(brute_data$statistics$R2)}} to \rsquarednum{\Sexpr{max(brute_data$statistics$R2)}}.
The {\ic} values ranged from \icnum{\Sexpr{min(brute_data$statistics[[ic]])}} to \icnum{\Sexpr{max(brute_data$statistics[[ic]])}}.
The ungrouped model gave an {\ic} value of \icnum{\Sexpr{brute_data$fully_separated_statistics[[ic]]}}.
\Cref{fig:ic} shows the distribution of {\ic} values from the models, with some models of interest marked.

\begin{figure}
	<<>>=
		hist(brute_data$statistics[[ic]],
			main="",
			xlab=ic_name,
			xaxs='i',
			yaxs='i'
		)
		abline(v = brute_data$fully_separated_statistics[[ic]], lwd=2, lty="dashed", col="green")
		abline(v = brute_data$fully_grouped_statistics[[ic]], lwd=2, lty="dashed", col="red")
	@
	
	\caption{%
		Histogram of the {\ic} values of Lotka--Volterra model fit with all possible groupings of interaction coefficients.
		The green line shows the {\ic} value (\icnum{\Sexpr{brute_data$fully_separated_statistics[[ic]]}}) of the ungrouped model, in which all competition coefficients are fitted independently.
		The red line shows the {\ic} value (\icnum{\Sexpr{brute_data$fully_grouped_statistics[[ic]]}}) of the fully grouped model, where every pair of species shares a single interaction coefficient.
	}
	\label{fig:ic}
\end{figure}

The ``best'' model, as indicated by {\ic}, was not the best with any surety; its Akaike weight indicated a probability of only \probnum{\Sexpr{max(brute_data$statistics[[ic_weight]])}} that it was the best.
\Cref{fig:best-model} shows the groupings and alpha values of this ``best'' model.
The ungrouped model had an {\ic} just \icnum{\Sexpr{brute_data$fully_separated_statistics[[ic]] - min(brute_data$statistics[[ic]])}} units from the most parsimonious model, but the total Akaike weight assigned to models more parsimonious than the ungrouped model was \probnum{\Sexpr{sum(brute_data$statistics[[ic_weight]][brute_data$statistics[[ic]] < brute_data$fully_separated_statistics[[ic]]])}}; this is the probability that some grouped model was more parsimonious than the ungrouped model.

Considering only models in which the rows and columns were grouped using the same grouping, the {\ic} values ranged from \icnum{\Sexpr{min(brute_data$equivalently_grouped_statistics[[ic]])}} to \icnum{\Sexpr{max(brute_data$equivalently_grouped_statistics[[ic]])}}; neither the best nor worst overall models had equivalently grouped rows and columns.
The total Akaike weight assigned to these models was \probnum{\Sexpr{brute_data$equivalently_grouped_weight}}; this was more than expected by chance (\probnum{\Sexpr{brute_data$equivalently_grouped_expected_weight}}), but not significantly so (Monte Carlo permutation test, $p=\probnum{\Sexpr{brute_data$equivalently_grouped_weight_p #$}}$).
This indicates that the most parsimonious model is not especially likely to be one that groups the rows and columns equivalently.

\begin{figure}
	\centering
	
	<<>>=
		best_model_index <- which.max(brute_data$statistics[[ic_weight]])
		best_row_grouping <- brute_data$get_row_grouping(best_model_index)
		best_col_grouping <- brute_data$get_col_grouping(best_model_index)
		best_alpha_matrix <- brute_data$parameters[[best_model_index]]$alpha_values
		
		ordering <- get_ordering(list(best_row_grouping, best_col_grouping))
		best_species_names <- brute_data$species_names[ordering]
		best_row_grouping <- best_row_grouping[ordering]
		best_col_grouping <- best_col_grouping[ordering]
		best_alpha_matrix <- best_alpha_matrix[ordering,ordering]
		
		best_row_coclassification <- as_coclassification_matrix(best_row_grouping)
		best_col_coclassification <- as_coclassification_matrix(best_col_grouping)
	@
	
	\begin{subfigure}{\textwidth}
		\centering
		<<>>=
			grouped_alpha_matrix(
				best_species_names,
				best_row_grouping,
				best_col_grouping,
				best_alpha_matrix
			)
		@
		\caption{The grouped alpha matrix.}
		\label{fig:best-alpha-matrix}
	\end{subfigure}
	
	\bigskip
	
	\begin{subfigure}{0.49\textwidth}
		\centering
		<<>>=
			minimal_coclassification_kable(
				best_col_coclassification,
				colourmap="coclassification", diagonal_colour="coclassification diagonal"
			)
		@
		\caption{The coclassification matrix of rows.}
		\label{fig:best-coclassification-cols}
	\end{subfigure}
	%
	\begin{subfigure}{0.49\textwidth}
		\centering
		<<>>=
			minimal_coclassification_kable(
				best_row_coclassification,
				colourmap="coclassification", diagonal_colour="coclassification diagonal"
			)
		@
		\caption{The coclassification matrix of columns.}
		\label{fig:best-coclassification-rows}
	\end{subfigure}
	
	\caption{%
		The groupings and competition coefficients of a grouped Lotka--Volterra model fitted to the six studied \emph{Drosophila} species.
		This represents the single model with the best {\ic} (\probnum{\Sexpr{brute_data$statistics[best_model_index,ic]}}).
		\Subref{fig:best-alpha-matrix} shows the competition coefficients, where a competition coefficient in a block represents the same coefficient being used for multiple interactions, per the groupings.
		\Subref{fig:best-coclassification-cols} and \subref{fig:best-coclassification-rows} show the coclassification matrices derived from the groupings of the columns and rows respectively.
		These coclassification matrices are averaged for all models, weighted by Akaike weights, to produce \cref{fig:coclassification}.
		Species have been reordered that species which are grouped together appear adjacent.
		The ordering is the same in \subref{fig:best-coclassification-cols} and \subref{fig:best-coclassification-rows} as shown in \subref{fig:best-alpha-matrix}.
	}
	\label{fig:best-model}
\end{figure}

\subsection{Coclassification of species}

Overall, no pair of species can confidently be said to be coclassified together in the row or column groupings; the highest probability of classification was \SI[round-mode=figures,round-precision=3]{\Sexpr{max(weighted_col_coclassification_matrix - diag(num_species), weighted_row_coclassification_matrix - diag(num_species))*100}}{\percent} (\cref{fig:coclassification}).
However, some pairs of species were far more likely to be coclassified than others, suggesting some structure to the best groupings.

The structure of the coclassifications was very different in the row groups than in the column groups.
Most pairs of species which had a high probability of being coclassified in one grouping had a very low probability of being coclassified in the other grouping.
Only one pair of species had a relatively high probability of being coclassified in both groupings: \emph{D. pallidifrons} and \emph{D. sulfurigaster}.
Overall, more coclassification occurred in the row groupings than in the column groupings.
A Mantel test of the coclassification matrix for the rows against that for the columns shows that there is no significant correlation between the two ($\mantelstat=\cornum{\Sexpr{mantel_cor(weighted_col_coclassification_matrix, weighted_row_coclassification_matrix)}}$, $p=\probnum{\Sexpr{mantel_p(weighted_col_coclassification_matrix, weighted_row_coclassification_matrix)}}$).

A relatively high likelihood of coclassification in the row groupings was typically transitive: for example, \emph{D. birchii}, \emph{D. pallidifrons} and \emph{D. sulfurigaster} each had a relatively high probability of being coclassified with one another.
More intransitivity was observed in the column groupings: \emph{D. pallidifrons} had a relatively high probability of being coclassified with \emph{D. sulfurigaster}, and \emph{D. sulfurigaster} had a substantial probability of being coclassified with \emph{D. simulans}, but \emph{D. pallidifrons} had a much lower probability of being coclassified with \emph{D. simulans}.

Neither the row nor column coclassification matrix was significantly correlated with a dissimilarity matrix based on species body size (column: $\mantelstat=\cornum{\Sexpr{mantel_cor(col_distance_matrix, body_weight_distance_matrix)}}$, $p=\probnum{\Sexpr{mantel_p(col_distance_matrix, body_weight_distance_matrix)}}$; row: $\mantelstat=\cornum{\Sexpr{mantel_cor(row_distance_matrix, body_weight_distance_matrix)}}$, $p=\probnum{\Sexpr{mantel_p(row_distance_matrix, body_weight_distance_matrix)}}$).

% DBS: Most journals frown upon or do not allow overly verbose subtitles on figures. So I've cut them down to be a bit more concise.
% DBS: But the fact that the labels say effects and responses reminds me of a lingering "doubt" I had when reading the main text. We talk almost entirely about rows and columns but there are a number of junctures where I feel like it would be easier to follow for people who aren't us if we were talking about responses and effects. As long as we're consistent, I'm fine either way. But we need to remember we're writing the paper for the audience and not for ourselves. ;)
\begin{figure}
	\centering
	\begin{subfigure}{\textwidth}
		\centering
		<<>>=
			weighted_coclassification_kable(
				weighted_col_coclassification_matrix[species_output_order,species_output_order],
				colourmap="coclassification", diagonal_colour="coclassification diagonal"
			)
		@
		\caption{Coclassification of competitive effects}
		\label{fig:coclassification-cols}
	\end{subfigure}
	
	\bigskip
	
	\begin{subfigure}{\textwidth}
		\centering
		<<>>=
			weighted_coclassification_kable(
				weighted_row_coclassification_matrix[species_output_order,species_output_order],
				colourmap="coclassification", diagonal_colour="coclassification diagonal"
			)
		@
		\caption{Coclassification of competitive responses}
		\label{fig:coclassification-rows}
	\end{subfigure}
	
	\caption{%
		Coclassification matrices of the Lotka--Volterra competitive effects and responses of the six studied \emph{Drosophila} species, weighted by Akaike weights.
		The cell for a pair of species represents the probability that the best grouping, as determined by the Akaike weights of the grouped models, places those two species in the same group.
		\Subref{fig:coclassification-cols} represents the grouping of species' competitive effects upon other species (columns of the interaction matrix), while \subref{fig:coclassification-rows} represents the grouping of species' responses to competition (rows of the interaction matrix).
	}
	\label{fig:coclassification}
\end{figure}

% DBS: I think a good figure would be to show the ungrouped estimated alpha matrix in one panel and the alpha matrix averaged across all partitions in a second panel, with lines drawn in the second to reflect the "optimal" partitioning of the co-classification matrices.

\section{Discussion}

We have shown that it is possible to fit a more parsimonious model of species interactions by grouping the interaction coefficients of species \emph{a posteriori}, and hence reducing the number of free parameters in the model.
Indeed, the results show that grouping species was likely to give a more parsimonious model (probability \probnum{\Sexpr{sum(brute_data$statistics[[ic_weight]][brute_data$statistics[[ic]] < brute_data$fully_separated_statistics[[ic]]])}}) than leaving them ungrouped.
Which grouping would give the most parsimonious model, however, could not be determined with confidence.
This result stands in contrast to the popular wisdom in ecology that species should form some sort of clear groups, be they the functional groups so often used \parencite{blondel2003guilds,kirwan2009diversity,boulangeat2012improving}, or taxonomic groups per a relationship between phylogeny and ecological niche \parencite{godoy2014phylogenetic,wilcox2018evolutionary}.
It also contrasts with previous studies that have succeeded in finding clear groups in other ecological contexts, such as in food webs \parencite{krause2003compartments,allesina2009food} and pollination networks \parencite{olesen2007modularity}.

One possible explanation is that species simply do not group to the same extent in a quantitative competitive context as in a binary network.
That said, the results suggest that this is unlikely as grouping was still likely to increase parsimony.
Further, there is no reason to suspect that species would not have clear similarities or dissimilarities in their ecological niches, and therefore their competitive effects and responses \parencite{XXX}.
In the present case, we cannot rule out the possibility that a lack of clarity in the groupings is instead a product of the study system.
All the species in this study were members of the same genus, \emph{Drosophila}, and as such were all rather similar.
A study system with species spanning multiple functional groups, or a broader taxonomy, might have shown clearer groupings.
Alternatively, the small number of species in the study might not have been sufficient for clear groups to be defined.
Alas, the brute force method we employed in this study has a very poor algorithmic complexity, preventing the application of the method to studies with more than seven or eight species. %DBS: Add in the number of models for both of these to emphasise the point.
As such, a better method would be required in order to test for grouping of species interactions among a larger set of species.

While the results could not definitely show the best grouping, it was clear that the appropriate grouping differed for the rows and columns.
That is, species that are similar in their response to competition may not be similar in the competitive effects they have on other species, and vice versa.
This should not be surprising, for it is known that different traits govern species competitive effects than their responses \parencite{goldberg1991competitive}.
Yet the assumption that species should group equivalently in these two regards is frequently made, often implicitly and without comment \parencite[e.g.][]{martorell2014testing,ives2003estimating,gross2015stability}.
Our results recommend more explicit questioning, and even testing, of that assumption when building future species interaction models.
%TODO: Discuss the fact that species were coclassified more in the rows than in the columns?

The intransitivity of coclassification in some instances even suggests that there may not be a single ``best'' grouping of the species, but rather two or more quite distinct and mutually exclusive groupings of similar validity.
A single trait like body size might therefore not be able to capture the multivariate nature of species' ecological niches \parencite{XXX}.
This could suggest that a Bayesian approach is worth exploring in the future, in which the outcome is not a definitive grouping but a distribution of valid groupings.
Alternatively, it may suggest adopting a mixed-membership approach in which a species can belong to more than one group \parencite{airoldi2008mixed}, reminiscent of the community-level drivers of \textcite{ovaskainen2017species}.

\FloatBarrier
\printbibliography
\end{document}
