#!/usr/bin/env Rscript
suppressPackageStartupMessages(library(optparse))
suppressPackageStartupMessages(library(magrittr))

##################
#Argument parsing.
##################

usage = "%prog DATA_TYPE FOCAL_OUTPUT_FILE RESPONSE_OUTPUT_FILE DESIGN_OUTPUT_FILE"
description = "Generates test data with known parameters, and outputs it in the three files desired by the C++ code.
Namely, the 0-indexed numerical focal species vector, the response variable vector, and the species density design matrix.
All are output as tab-separated matrices, without column headers, with vectors in the form column vectors.
DATA_TYPE must be 'pop', for individual response data."
option_list <- list(
	make_option(
		c("-n", "--n"), dest = "n", type = "integer", default = 3,
		help = "The number of replicates of each experiment to run."
	),
	make_option(
		c("-s", "--seed"), dest = "seed", type = "integer", default = 0,
		help = "The seed for the random number generator."
	),
	make_option(
		c("-r", "--rowdiff"), dest = "row_diff", type = "double", default = 0,
		help = "The difference between the mean alpha values of the rows, as a proportion of the total alpha value."
	),
	make_option(
		c("-c", "--coldiff"), dest = "col_diff", type = "double", default = 0,
		help = "The difference between the mean alpha values of the columns, as a proportion of the total alpha value."
	)
)
parser <- OptionParser(usage = usage, description = description, option_list = option_list)
arguments <- parse_args(parser, positional_arguments = 4)

data_type <- arguments$args[1]
focal_outfile <- arguments$args[2]
response_outfile <- arguments$args[3]
design_outfile <- arguments$args[4]

attach(arguments$options)

if(data_type != "pop") {
	stop("Invalid data type requested.")
}

set.seed(seed)

############################
#Set known parameter values.
############################

#TODO: Obtain these programmatically from the TCL results.
growth_rate <- 6.102122 #The mean growth rate for all species in all models in tcl/brute.data
mean_alpha <- 0.0290139 #The alpha for the fully grouped model in tcl/brute.data
dispersion <- 0.2669737 #The mean dispersion parameter in tcl/rjmcmc.data

species_per_group <- 2
num_species <- species_per_group * 2 #There are always two groups.

growth_rates <- rep(growth_rate, num_species)

competition_coefficients <- mean_alpha * matrix(c(
	rep(c(1 - row_diff / 2 - col_diff / 2, 1 - row_diff / 2 + col_diff / 2), each = species_per_group, times = species_per_group),
	rep(c(1 + row_diff / 2 - col_diff / 2, 1 + row_diff / 2 + col_diff / 2), each = species_per_group, times = species_per_group)
), nrow = num_species, ncol = num_species, byrow = TRUE)

#############################################
#Generate the design matrix and focal vector.
#############################################

base_design_matrix_single <- c(6, 18, 30)
base_design_matrix_pairwise <- matrix(c(
	6, 6,
	6, 12,
	6, 18,
	6, 24,
	12, 6,
	18, 6,
	24, 6
), ncol = 2, byrow = TRUE)

design_matrix_single <- do.call(rbind, lapply(1:num_species, function(i) {
	mat <- matrix(0, nrow = length(base_design_matrix_single), ncol = num_species)
	mat[,i] <- base_design_matrix_single
	return(mat)
}))
focal_vector_single <- rep(1:num_species, each = length(base_design_matrix_single))

combinations <- gtools::combinations(num_species, ncol(base_design_matrix_pairwise))
design_matrix_pairwise <- do.call(rbind, lapply(1:nrow(combinations), function(i) {
	mat <- matrix(0, nrow = nrow(base_design_matrix_pairwise), ncol = num_species)
	for(j in seq_along(combinations[i,])) {
		mat[,combinations[i,j]] <- base_design_matrix_pairwise[,j]
	}
	return(mat)
}))
focal_vector_pairwise <- as.vector(t(combinations))

design_matrix_pairwise <- design_matrix_pairwise[rep(1:nrow(design_matrix_pairwise), each = ncol(base_design_matrix_pairwise)),] #Duplicate each row in the design matrix, once for each focal.
focal_vector_pairwise <- rep(focal_vector_pairwise, each = nrow(base_design_matrix_pairwise)) #Repeat the focal vector, for each combination in the design matrix.

#Join the pairwise and single species design matrices and focal vectors.
design_matrix <- rbind(design_matrix_single, design_matrix_pairwise)
focal_vector <- c(focal_vector_single, focal_vector_pairwise)

#Replicate the rows of the design matrix and focal vector.
design_matrix <- design_matrix[rep(1:nrow(design_matrix), each = n),]
focal_vector <- rep(focal_vector, each = n)

##############################
#Generate the response vector.
##############################

get_predicted_reponse <- function(obs) {
	focal <- focal_vector[obs]
	
	focal_growth_rate <- growth_rates[focal]
	focal_density <- design_matrix[obs, focal]
	
	focal_competition_coefficients <- as.vector(competition_coefficients[focal,])
	competitor_densities <- as.vector(design_matrix[obs,])
	
	predicted_response <- focal_growth_rate * focal_density / (1 + sum(focal_competition_coefficients * competitor_densities))
	return(predicted_response)
}

rnbinom2 <- function(n, mean, dispersion) {
	#Using the negative binomial parameterisation from the C code.
	rnbinom(n, size = 1 / dispersion, prob = (1 / dispersion) / (mean + 1 / dispersion))
}

predicted_response_vector <- sapply(1:nrow(design_matrix), get_predicted_reponse)

response_vector <- rnbinom2(length(predicted_response_vector), predicted_response_vector, dispersion)

##############################################
#Turn the outputs into matrices, and finalise.
##############################################

focal_vector <- focal_vector - 1 #Make it 0-indexed.

focal_vector %<>% matrix(ncol=1)
response_vector %<>% matrix(ncol=1)

###################
#Print the outputs.
###################

print_table <- function(table, outfile) {
	write.table(table, outfile, row.names = FALSE, col.names = FALSE, quote = FALSE, sep = "\t")
}

print_table(focal_vector, focal_outfile)
print_table(response_vector, response_outfile)
print_table(design_matrix, design_outfile)
